# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pmod_TMP3_Const.xdc

# Block Designs: bd/Pmod_TMP3/Pmod_TMP3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TMP3 || ORIG_REF_NAME==Pmod_TMP3} -quiet] -quiet

# IP: bd/Pmod_TMP3/ip/Pmod_TMP3_PmodTMP3_0_0/Pmod_TMP3_PmodTMP3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TMP3_PmodTMP3_0_0 || ORIG_REF_NAME==Pmod_TMP3_PmodTMP3_0_0} -quiet] -quiet

# IP: bd/Pmod_TMP3/ip/Pmod_TMP3_processing_system7_0_0/Pmod_TMP3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TMP3_processing_system7_0_0 || ORIG_REF_NAME==Pmod_TMP3_processing_system7_0_0} -quiet] -quiet

# IP: bd/Pmod_TMP3/ip/Pmod_TMP3_auto_pc_0/Pmod_TMP3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TMP3_auto_pc_0 || ORIG_REF_NAME==Pmod_TMP3_auto_pc_0} -quiet] -quiet

# IP: bd/Pmod_TMP3/ip/Pmod_TMP3_ps7_0_axi_periph_0/Pmod_TMP3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TMP3_ps7_0_axi_periph_0 || ORIG_REF_NAME==Pmod_TMP3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pmod_TMP3/ip/Pmod_TMP3_rst_ps7_0_50M_0/Pmod_TMP3_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TMP3_rst_ps7_0_50M_0 || ORIG_REF_NAME==Pmod_TMP3_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Pmod_TMP3/Pmod_TMP3.gen/sources_1/bd/Pmod_TMP3/Pmod_TMP3_ooc.xdc
