# Pmod JC
set_property PACKAGE_PIN V15 [get_ports Pmod_out_0_pin1_io]
set_property PACKAGE_PIN W15 [get_ports Pmod_out_0_pin2_io]
set_property PACKAGE_PIN T11 [get_ports Pmod_out_0_pin3_io]
set_property PACKAGE_PIN T10 [get_ports Pmod_out_0_pin4_io]
set_property PACKAGE_PIN W14 [get_ports Pmod_out_0_pin7_io]
set_property PACKAGE_PIN Y14 [get_ports Pmod_out_0_pin8_io]
set_property PACKAGE_PIN T12 [get_ports Pmod_out_0_pin9_io]
set_property PACKAGE_PIN U12 [get_ports Pmod_out_0_pin10_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin1_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin2_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin4_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin7_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin8_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin9_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin10_io]
