set_property SRC_FILE_INFO {cfile:C:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Pmod_TC1/Pmod_TC1.srcs/constrs_1/new/Pmod_TC1_Const.xdc rfile:../../../Pmod_TC1.srcs/constrs_1/new/Pmod_TC1_Const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports CS]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports MOSI]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports MISO]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports SCK]
